version: 0.1

phases:
    install:
        commands:
            - echo installing nodejs...
            - echo curl -sL https://deb.nodesource.com/setup_12.x | bash -
            - apt-get install -y nodejs
            - echo installing yarn...
            - npm install --global yarn 
    pre-builds:
        commands:
            - echo installing dependencies...
            - npm install
    build:
        commands:
            - echo building...
            - npm run build

artifacts:
    files:
        - "**/*"
    discard-path: no
    base-directory: dist
